collections:
  - name: community.general
  - name: community.mongodb
    version: '1.3'
  - name: containers.podman
  - name: ansible.posix
  - name: community.kubernetes
  - name: kubernetes.core
  - name: google.cloud
  - name: community.docker 
roles:
  - newrelic.newrelic-infra
